version: "3.8"
services:
  postgres:
    image: "postgres:12.2"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
volumes:
  postgres:
